#!/usr/bin/env ruby

[
  [10,   10_000],
  [100,  10_000],
  [1000, 10_000],
  [100,  50_000],
  [1000, 50_000],
].each do |concurrency, requests|
  puts
  puts "#{requests} requests, concurrency #{ concurrency }"
  puts "-" * 50
  
  system("ab -c #{ concurrency } -n #{ requests } http://localhost:3000/")
  puts
end